import { afterEach, describe, expect, it, vi } from 'vitest';

import { DEVICE_TOKEN_STORAGE_KEY } from './authHeaders';
import * as authHeaders from './authHeaders';
import {
  claimDevice,
  createPairingCode,
  getCurrentPairedDevice,
  revokeCurrentPairedDevice,
  startDeviceRevocationMonitor,
} from './devicePairing';

const device = {
  id: '0123456789abcdef01234567',
  name: 'Tablet',
  scopes: ['chat', 'read_private'],
  created_at: 1,
  last_seen_at: null,
  expires_at: null,
  revoked_at: null,
};

describe('device pairing client', () => {
  afterEach(() => {
    localStorage.clear();
    sessionStorage.clear();
    vi.unstubAllGlobals();
  });

  it('uses the HttpOnly cookie from pairing without persisting a new bearer', async () => {
    const fetchMock = vi.fn().mockResolvedValue(new Response(JSON.stringify({
      ok: true,
      token: 'txd_new-secret',
      device,
    }), { status: 200, headers: { 'Content-Type': 'application/json' } }));
    vi.stubGlobal('fetch', fetchMock);

    expect(await claimDevice('ABCD-EFGH', 'Tablet')).toEqual(device);
    expect(localStorage.getItem(DEVICE_TOKEN_STORAGE_KEY)).toBeNull();
    expect(sessionStorage.getItem(DEVICE_TOKEN_STORAGE_KEY)).toBeNull();
    expect(fetchMock.mock.calls[0][1]?.credentials).toBe('include');
    expect(fetchMock.mock.calls[0][1]?.headers).toEqual({ 'Content-Type': 'application/json' });
    expect(JSON.parse(fetchMock.mock.calls[0][1].body)).toEqual({
      code: 'ABCD-EFGH',
      device_name: 'Tablet',
    });
  });

  it('includes only safe remote scopes in codes generated by the host', async () => {
    const fetchMock = vi.fn().mockResolvedValue(new Response(JSON.stringify({
      ok: true,
      code: 'ABCD-EFGH',
      expires_at: 123,
      scopes: ['chat', 'read_private', 'web'],
    }), { status: 200, headers: { 'Content-Type': 'application/json' } }));
    vi.stubGlobal('fetch', fetchMock);

    await createPairingCode();

    expect(JSON.parse(fetchMock.mock.calls[0][1].body)).toEqual({
      scopes: ['chat', 'read_private', 'web'],
      ttl_seconds: 300,
    });
  });

  it('removes revoked or rejected credentials from the session', async () => {
    const revoked = vi.fn();
    window.addEventListener('trinaxai-device-access-revoked', revoked, { once: true });
    localStorage.setItem(DEVICE_TOKEN_STORAGE_KEY, 'expired');
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response('{}', { status: 403 })));
    expect(await getCurrentPairedDevice()).toBeNull();
    expect(sessionStorage.getItem(DEVICE_TOKEN_STORAGE_KEY)).toBeNull();
    expect(localStorage.getItem(DEVICE_TOKEN_STORAGE_KEY)).toBeNull();
    expect(revoked).toHaveBeenCalledOnce();
  });

  it('revokes itself with the device credential and then erases it', async () => {
    const revoked = vi.fn();
    window.addEventListener('trinaxai-device-access-revoked', revoked, { once: true });
    localStorage.setItem(DEVICE_TOKEN_STORAGE_KEY, 'txd_token');
    const fetchMock = vi.fn().mockResolvedValue(new Response(JSON.stringify({ ok: true, device }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    }));
    vi.stubGlobal('fetch', fetchMock);
    await revokeCurrentPairedDevice();
    expect(fetchMock.mock.calls[0][1]).toMatchObject({
      method: 'DELETE',
      headers: { 'X-TrinaxAI-Device-Token': 'txd_token' },
    });
    expect(sessionStorage.getItem(DEVICE_TOKEN_STORAGE_KEY)).toBeNull();
    expect(localStorage.getItem(DEVICE_TOKEN_STORAGE_KEY)).toBeNull();
    expect(revoked).toHaveBeenCalledOnce();
  });

  it('reads a cookie-only device session without adding a bearer header', async () => {
    const fetchMock = vi.fn().mockResolvedValue(new Response(JSON.stringify({ device }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    }));
    vi.stubGlobal('fetch', fetchMock);

    expect(await getCurrentPairedDevice()).toEqual(device);
    expect(fetchMock.mock.calls[0][1]?.credentials).toBe('include');
    expect(fetchMock.mock.calls[0][1]?.headers).toBeUndefined();
  });

  it('migrates an existing legacy bearer through /me and then removes it', async () => {
    localStorage.setItem(DEVICE_TOKEN_STORAGE_KEY, 'legacy-token');
    sessionStorage.setItem(DEVICE_TOKEN_STORAGE_KEY, 'legacy-session-token');
    const fetchMock = vi.fn().mockResolvedValue(new Response(JSON.stringify({ device }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    }));
    vi.stubGlobal('fetch', fetchMock);

    expect(await getCurrentPairedDevice()).toEqual(device);
    expect(localStorage.getItem(DEVICE_TOKEN_STORAGE_KEY)).toBeNull();
    expect(sessionStorage.getItem(DEVICE_TOKEN_STORAGE_KEY)).toBeNull();
    expect(fetchMock.mock.calls[0][1]?.headers).toEqual({ 'X-TrinaxAI-Device-Token': 'legacy-token' });
  });

  it('does not poll paired-device status from the privileged localhost host', () => {
    localStorage.setItem(DEVICE_TOKEN_STORAGE_KEY, 'stale');
    const fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);

    const cleanup = startDeviceRevocationMonitor();
    expect(fetchMock).not.toHaveBeenCalled();
    cleanup();
  });

  it('backs off failed revocation fallback checks instead of polling every 2 seconds', async () => {
    vi.useFakeTimers();
    vi.spyOn(authHeaders, 'isLocalHostBrowser').mockReturnValue(false);
    localStorage.setItem(DEVICE_TOKEN_STORAGE_KEY, 'txd_token');
    const fetchMock = vi.fn()
      .mockRejectedValueOnce(new Error('offline'))
      .mockResolvedValue(new Response(JSON.stringify({ device }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' },
      }));
    vi.stubGlobal('fetch', fetchMock);

    const cleanup = startDeviceRevocationMonitor();
    expect(fetchMock).toHaveBeenCalledTimes(1);
    await vi.advanceTimersByTimeAsync(0);
    await vi.advanceTimersByTimeAsync(2_000);
    expect(fetchMock).toHaveBeenCalledTimes(1);
    await vi.advanceTimersByTimeAsync(57_000);
    expect(fetchMock).toHaveBeenCalledTimes(1);
    await vi.advanceTimersByTimeAsync(1_000);
    expect(fetchMock).toHaveBeenCalledTimes(2);

    cleanup();
  });
});
